# Generated by Django 4.1 on 2022-09-10 14:41

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('A', 'Apple'), ('S', 'Samsung')], max_length=25)),
                ('model', models.CharField(choices=[('7', 'Iphone 7'), ('8', 'Iphone 8'), ('X', 'Iphone X'), ('11', 'Iphone 11'), ('12', 'Iphone 12'), ('13', 'Iphone 13')], max_length=25)),
                ('variant', models.CharField(choices=[('B', 'Base'), ('Pl', 'Plus'), ('Pr', 'Pro'), ('Prm', 'Promax')], max_length=25)),
                ('storage', models.IntegerField()),
                ('battery', models.CharField(choices=[('A', 'Above 90%'), ('B', '80% to 90%'), ('C', 'Below 90%')], max_length=25)),
                ('touchorfaceid', models.CharField(max_length=25)),
                ('truetone', models.BooleanField(default=True)),
                ('screen_issues', models.BooleanField(default=False)),
                ('body_issues', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=25)),
                ('profile_pic', models.ImageField(default='profileimages/profiledefault.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.phone')),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(default='phoneimages/default.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
                ('price', models.FloatField(null=True)),
                ('negotiable', models.BooleanField()),
            ],
        ),
    ]
