# Generated by Django 4.1 on 2022-09-15 07:52

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=25)),
                ('profile_pic', models.ImageField(default='profileimages/profiledefault.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('storage', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('battery', models.CharField(max_length=25)),
                ('screen_size', models.CharField(max_length=25)),
                ('camera', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('price', models.FloatField(null=True)),
                ('negotiable', models.BooleanField()),
                ('image1', models.ImageField(default='phoneimages/default.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
                ('image2', models.ImageField(default='phoneimages/default.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
                ('image3', models.ImageField(default='phoneimages/default.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
                ('image4', models.ImageField(default='phoneimages/default.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
