# Generated by Django 4.1 on 2022-09-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_phone_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='owner',
            new_name='user',
        ),
    ]
